import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         {/* HEADER */}
        <header className="bg-blue-600 text-white p-4">
          <nav className="flex gap-4">
            <Link href="/" className="hover:underline">Accueil</Link>
            <Link href="/about" className="hover:underline">About</Link>
            <Link href="/contact" className="hover:underline">Contact</Link>
          </nav>
        </header>

        {/* CONTENU */}
        <main className="flex-1 p-6">
          {children}
        </main>

        {/* FOOTER */}
        <footer className="bg-gray-800 text-white p-4 text-center">
          © 2025 – Mon App Next.js
        </footer>
      </body>
    </html>
  );
}
